name = "AndersonPlus"
uuid = "77032a0f-8d0d-4e3c-a050-59324243496d"
authors = ["Tobias Bretschneider"]
version = "1.0.0-DEV"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[compat]
AbstractFFTs = "1.5.0"
Debugger = "0.7.10"
FFTW = "1.8.1"
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
QuadGK = "2.11.1"
SparseArrays = "1.11.0"
Wavelets = "0.10.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
